### ISSUE TITLE
Input max width problem

### ISSUE THREAD

**Issue by alpercun** [aykutkardas/easy-regex#1]
It looks like we need the maximum width for the input. Otherwise, the image will be distorted when it exceeds the area.
<img width="1143" alt="Screen Shot 2021-09-05 at 8 55 43 PM" src="https://user-images.githubusercontent.com/32914083/132136681-f0ce8202-7d98-45d1-8427-4fe678f28b2f.png">

**Comment by alpercun** [comment]
I can fix that issue btw.

**Comment by aykutkardas** [comment]
Thanks @alpercun. I am waiting for your help.
